baseURL = 'https://clover-leaf.github.io'
languageCode = 'en-us'
title = 'The blog of Clover-leaf'
theme = '

[params]
  author = "Clover-leaf"
  description = "A blog about my learning path"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/clover-leaf"